"""Schemas for the Extractor package.

All Pydantic models used by the Extractor. Internal models are
prefixed with an underscore and excluded from the barrel.

Notes
-----
Each model uses pydantic.Field with ``description`` and where
relevant, ``examples`` to fully document the contract.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ── Public schemas ───────────────────────────────────────────────────────────


class Sensitivity(BaseModel):
    """Assessment of whether input text contains sensitive information.

    Attributes
    ----------
    is_sensitive : bool
        True if any sensitive information was found.
    rationale : str
        Explanation of the assessment in Korean.

    Examples
    --------
    >>> s = Sensitivity(is_sensitive=True, rationale="주민등록번호(901212-1234567)가 탐지됨")
    >>> s.is_sensitive
    True
    """

    is_sensitive: bool = Field(
        ...,
        description="Whether sensitive information was detected in the text.",
        examples=[True, False],
    )
    rationale: str = Field(
        ...,
        description="Human-readable explanation of the assessment (Korean).",
        examples=[
            "주민등록번호(901212-1234567)가 탐지되어 민감 정보로 분류됩니다.",
            "민감 정보가 발견되지 않았습니다.",
        ],
    )


class ExtractionRecord(BaseModel):
    """A single detected sensitive span.

    Attributes
    ----------
    category : str
        SCREAMING_SNAKE_CASE tag generated by the SLM.
    span : str
        Exact substring that was detected in the original text.
    confidence : float
        Detection confidence, clipped to [0.0, 1.0].
    start : int
        Character offset where the span begins (0-indexed).
    end : int
        Character offset where the span ends (exclusive, 0-indexed).

    Examples
    --------
    >>> r = ExtractionRecord(category="RESIDENT_REGISTRATION_NUMBER", span="901212-1234567", confidence=0.98, start=7, end=21)
    >>> r.make_placeholder(1)
    '[RESIDENT_REGISTRATION_NUMBER#1]'
    """

    category: str = Field(
        ...,
        description="SCREAMING_SNAKE_CASE tag (e.g., RESIDENT_REGISTRATION_NUMBER).",
        examples=["RESIDENT_REGISTRATION_NUMBER", "NOVEL_RESEARCH_CONCEPT"],
    )
    span: str = Field(
        ...,
        description="Exact substring matched in the original text.",
        examples=["901212-1234567", "TSMC 3nm 공정 채택"],
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Detection confidence score.",
        examples=[0.98, 0.85],
    )
    start: int = Field(
        ...,
        ge=0,
        description="Start character index in the original text (0-indexed).",
        examples=[7],
    )
    end: int = Field(
        ...,
        ge=0,
        description="End character index in the original text (exclusive, 0-indexed).",
        examples=[21],
    )

    def make_placeholder(self, index: int) -> str:
        """Generate a stable placeholder for masking.

        Parameters
        ----------
        index : int
            Instance counter for this category (1-indexed).

        Returns
        -------
        str
            Placeholder string such as ``[RESIDENT_REGISTRATION_NUMBER#1]``.

        Examples
        --------
        >>> record = ExtractionRecord(category="RESIDENT_REGISTRATION_NUMBER", ...)
        >>> record.make_placeholder(1)
        '[RESIDENT_REGISTRATION_NUMBER#1]'
        """
        return f"[{self.category}#{index}]"


class ExtractionResult(BaseModel):
    """Full result of the extraction phase.

    Attributes
    ----------
    sensitivity : Sensitivity
        Whether sensitive information was found and why.
    records : list of ExtractionRecord
        Validated extraction records (empty if nothing was found).

    Examples
    --------
    >>> s = Sensitivity(is_sensitive=True, rationale="탐지됨")
    >>> r = ExtractionResult(sensitivity=s)
    >>> r.records
    []
    """

    sensitivity: Sensitivity = Field(
        ...,
        description="Sensitivity assessment including rationale.",
        examples=[Sensitivity(is_sensitive=True, rationale="주민등록번호 탐지")],
    )
    records: list[ExtractionRecord] = Field(
        default_factory=list,
        description="Validated extraction records.",
        examples=[[ExtractionRecord(category="RESIDENT_REGISTRATION_NUMBER", span="901212-1234567", confidence=0.98, start=7, end=21)]],
    )


# ── Internal schemas (SLM output contracts) ──────────────────────────────────
# The following are the Pydantic shapes the SLM is asked to produce.
# They are NOT part of the public API.


class _ExtractedItem(BaseModel):
    """Shape the SLM produces for a single span.

    Examples
    --------
    >>> item = _ExtractedItem(category="RRN", span="901212-1234567", confidence=0.98, start=7, end=21)
    """

    category: str = Field(
        ...,
        description="SCREAMING_SNAKE_CASE tag assigned by the SLM.",
        examples=["RESIDENT_REGISTRATION_NUMBER", "FABRICATION_PROCESS_DECISION"],
    )
    span: str = Field(
        ...,
        description="Exact substring from the input.",
        examples=["901212-1234567"],
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Detection confidence.",
        examples=[0.98],
    )
    start: int = Field(
        ...,
        ge=0,
        description="Start character index.",
        examples=[7],
    )
    end: int = Field(
        ...,
        ge=0,
        description="End character index.",
        examples=[21],
    )


class _ExtractedOutput(BaseModel):
    """Shape the SLM produces for the complete extraction call.

    Examples
    --------
    >>> s = Sensitivity(is_sensitive=True, rationale="탐지됨")
    >>> o = _ExtractedOutput(sensitivity=s)
    >>> o.records
    []
    """

    sensitivity: Sensitivity = Field(
        ...,
        description="Sensitivity assessment from the SLM.",
        examples=[Sensitivity(is_sensitive=True, rationale="주민등록번호 탐지")],
    )
    records: list[_ExtractedItem] = Field(
        default_factory=list,
        description="Raw extracted items from the SLM.",
        examples=[[_ExtractedItem(category="RESIDENT_REGISTRATION_NUMBER", span="901212-1234567", confidence=0.98, start=7, end=21)]],
    )
